import type { Metadata } from "next";
import { ReactNode } from 'react';
//import { getTranslations } from "@/src/lib/getTranslations";

//import '../../styles/globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LocaleParams = Promise<{ lang: 'en' | 'es' }>

interface LayoutProps {
  children: ReactNode
  params: LocaleParams
}

export default async function RootLayout({
  children,
  params,
}: LayoutProps) {
  const { lang } = await params

  return (
    <html lang={lang}>
      <body>
        {children}
      </body>
    </html>
  );
}
